name: Test

on:
  push:
    branches:
      - master
  pull_request:

env:
  DOCKER_FLAGS: ""
  CI: 1

jobs:
  output:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: diff output
        run: rake docker_test_output
  linux:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
        group:
          - group1
          - group2
          - group3
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: run tests
        env:
          RUBY: ruby3.3
        run: |
          export GLOB=$(ruby spec/support/split_specs.rb 3 ${{ matrix.group }})
          rake docker_test_${{ matrix.compiler }}
  macos:
    runs-on: macos-12
    strategy:
      matrix:
        group:
          - group1
          - group2
          - group3
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: install ruby
        run: |
          brew update
          brew uninstall -f --ignore-dependencies ruby
          brew uninstall -f --ignore-dependencies ruby@3.0
          rm -rf /usr/local/lib/ruby/gems/3.0.0 /usr/local/opt/ruby@3.0
          brew install ruby@3.3
      - name: check ruby
        env:
          PATH: "/usr/local/opt/ruby/bin:/usr/local/bin/:/usr/bin"
        run: |
          which ruby
          ruby --version
          which bundle
      - name: install build tools
        run: brew install autoconf automake libtool pkg-config
      - name: install openssl
        run: brew install openssl
      - name: install libffi
        run: brew install libffi
      - name: test with clang on macOS
        env:
          PKG_CONFIG_PATH: /usr/local/opt/openssl@3/lib/pkgconfig:/opt/homebrew/opt/openssl@3/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/opt/homebrew/opt/libffi/lib/pkgconfig
        run: |
          export GLOB=$(ruby spec/support/split_specs.rb 3 ${{ matrix.group }})
          export PATH="/usr/local/opt/ruby/bin:$PATH"
          rake test
  self-hosted:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: build self-hosted binary
        run: rake docker_test_self_hosted
  asan:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: test with AddressSanitizer
        run: rake docker_test_asan
