name: Test

on:
  push:
    branches:
      - master
  pull_request:

env:
  DOCKER_FLAGS: ""
  CI: 1

jobs:
  linux:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ruby_version:
          - ruby3.0
          - ruby3.1
          - ruby3.2
          - ruby3.3
        compiler:
          - gcc
          - clang
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: run tests
        run: rake docker_test_${{ matrix.compiler }} RUBY=${{ matrix.ruby_version }}
  macos:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: install ruby
        run: brew install ruby autoconf automake libtool pkg-config
      - name: install openssl
        run: brew install openssl
      - name: install libffi
        run: brew install libffi
      - name: test with clang on macOS
        env:
          PKG_CONFIG_PATH: /usr/local/opt/openssl@3/lib/pkgconfig:/opt/homebrew/opt/openssl@3/lib/pkgconfig:/usr/local/opt/libffi/lib/pkgconfig:/opt/homebrew/opt/libffi/lib/pkgconfig
        run: rake test
  self-hosted:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: build self-hosted binary
        run: rake docker_test_self_hosted
  asan:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: test with AddressSanitizer
        run: rake docker_test_asan
