name: Run all tests with the bootstrapped self-hosted compiler

on:
  schedule:
    - cron: "40 2 * * *"

jobs:
  specs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: run tests
        run: rake docker_test_self_hosted_full RUBY=ruby3.2
